### ISSUE TITLE
great lib... no sort? 

### ISSUE THREAD

**Issue by born2net** [fknop/angular-pipes#1]
great lib... no sort? 

maybe add: https://plnkr.co/edit/DHLVc0?p=preview

regards

Sean

**Comment by fknop** [comment]
Hello,

I was planning on adding it this week-end when I have the time, but this looks good I'll take a look later :+1: 

fknop

**Comment by fknop** [comment]
1.2.0 is published on npm. I added the `orderBy`.

**Comment by born2net** [comment]
sweet, tx!
you can checkout my Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean
