### ISSUE TITLE
Build Fails - Angular V5

### ISSUE THREAD

**Issue by amanpreet-dev** [fknop/angular-pipes#108]
**I'm submitting a ...** (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
Angular 5
NodeJs - 10.16.0
OS - Mac
Build generation fails

`ERROR in ./node_modules/angular-pipes/node_modules/tslib/tslib.es6.js
Module build failed: TypeError: Cannot read property 'type' of undefined`
**Expected behavior**
Build generation should be a success

**Minimal reproduction of the problem with instructions**
`ng serve` works perfectly.
`ng build --prod --env=staging --aot --buildOptimizer` is used for build process
TS 2.4.2 is used.

**What is the motivation / use case for changing the behavior?**

**Comment by fknop** [comment]
Hi, 

For Angular 5 you need to use an older version of this package. 
https://github.com/fknop/angular-pipes/blob/master/CHANGELOG.md#800

**Comment by amanpreet-dev** [comment]
Thanks, it worked.
One question do we have version wise breakup of documentation?

**Comment by fknop** [comment]
Unfortunately, I don't have links to the documentation for v5 but it is versioned in Git so you might find it by going back in the history.
