### ISSUE TITLE
ng2 beta 0.16 changed how pipes work :(

### ISSUE THREAD

**Issue by born2net** [fknop/angular-pipes#11]
pipes now take a variable number of arguments, and not an array that contains all arguments.

**Comment by fknop** [comment]
Yep I know, I'm going to change that as soon as possible !

**Comment by fknop** [comment]
I'll add a note on the README

**Comment by fknop** [comment]
It should just break the tests tho, right ?

**Comment by born2net** [comment]
I am not sure, trying to fix my code... :)

**Comment by fknop** [comment]
I was wrong, doesn't only break the tests, obviously. I've added a warning on the README until I change that. I'll try to do it tonight.
