### ISSUE TITLE
Created a fork

### ISSUE THREAD

**Issue by santoshyadavdev** [fknop/angular-pipes#113]
Hey everyone, I have created a fork https://github.com/ngx-builders/angular-pipes and updated and released a new version

- https://www.npmjs.com/package/ngx2-pipes
- 13.0.0

this is in APF (Angular Package Format) once this package is active I am happy to open a PR to keep this package updated.

**Comment by jamie-pate** [comment]
I guess there needs to be another published version on npmjs to remove  'not actively maintained' from the readme in the fork? :D

**Comment by santoshyadavdev** [comment]
Sure will update thanks for finding it out, will close this issue as well.
