### ISSUE TITLE
Tripleslash references

### ISSUE THREAD

**Issue by JulioC** [fknop/angular-pipes#15]
Trying build my project after including the pipes throws an error: "Exported external package typings file cannot contain tripleslash references."

The code is simple as:

```
import {TailPipe, HeadPipe} from 'angular-pipes';
@Component({
  selector: 'page',
  pipes: [TailPipe, HeadPipe],
  directives: [BannerComponent, PageLinkDirective],
  template: `{{list | head}}
    <spand *ngFor="let item of list | tail">{{item}}</span>
  `
})
export class Page extends BasePage {
  list = [1,2,3];
}
```

I'm building with Angular2 rc.1, angular-pipes 1.6.0, node 6.0.0, typings 0.8.1

Removing the tripleslashes from `angular-pipes/index.ts` solved it.

**Comment by JulioC** [comment]
Maybe related to https://github.com/angular/angular/issues/8513 ?

**Comment by fknop** [comment]
`1.6.0` is not supporting RC.1. It will come for `2.0.0`, it's pushed on GitHub, I just have to do some more changes before I publish it on npm.

**Comment by JulioC** [comment]
Thanks, I'll close the issue.

**Comment by fknop** [comment]
It's weird that the file you are requesting is the Typescript file. The main file in the package.json is targeting the compiled index.js. I've already has a complain about this. I'll check

**Comment by fknop** [comment]
Question: Are you using SystemJS ?

**Comment by JulioC** [comment]
I'm using Webpack.

My project is based on https://github.com/AngularClass/angular2-webpack-starter/, we could use angular-pipes with that to try reproduce the issue.

**Comment by JulioC** [comment]
On my `tsconfig.json` I have `compilerOptions.module` set to `commonjs`. From [TS docs](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#adjustments-in-module-resolution-logic), that means TS will use 'node' module resolution.

On [TS docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html#node), lookup order is defined as:

    /root/src/moduleB.ts
    /root/src/moduleB.tsx
    /root/src/moduleB.d.ts
    /root/src/moduleB/package.json (if it specifies a "typings" property)
    /root/src/moduleB/index.ts
    /root/src/moduleB/index.tsx
    /root/src/moduleB/index.d.ts

Maybe that's why we are having this issue.

**Comment by fknop** [comment]
I don't know webpack, but have you tried adding an alias like this ? https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.common.js#L78

**Comment by JulioC** [comment]
Tried adding `'angular-pipes': helpers.root('node_modules/angular-pipes/pipes/index.js')`, without success.

**Comment by fknop** [comment]
It's probably because it doesnt support RC1 yet. What's the error ?

**Comment by JulioC** [comment]
The same error as before. I believe that's just related to the alias not working.

I'd prefer not adding an alias for that, instead just fix the `index.ts` resolving issue.

**Comment by fknop** [comment]
Yes, I'll release it tomorrow

**Comment by fknop** [comment]
So I published it sooner. I actually removed the reference, it should probably work now.

**Comment by JulioC** [comment]
With 2.0.0 it's working, but still resolves `index.ts` as the main file.

**Comment by fknop** [comment]
It's probably webpack that resolves module differently than SystemJS.

**Comment by fknop** [comment]
I'm closing this, I found it in the doc of webpack: 

http://webpack.github.io/docs/configuration.html#resolve-extensions

The `.ts` is first in your configuration.
