### ISSUE TITLE
Error: Can't export pipe EmptyPipe from Ng2ArrayPipesModule as it was neither declared nor imported!

### ISSUE THREAD

**Issue by GitHubish** [fknop/angular-pipes#23]
Hello,

I have this error when importing the NgModule ( Angular2 RC6 ).

Thanks and great job ;)

**Comment by fknop** [comment]
Could you paste me your code ? (just to be sure where it's coming from)

**Comment by fknop** [comment]
3.0.2 version is published. You can try it and close this issue if it works.

**Comment by GitHubish** [comment]
It's ok ! 

Thanks !
