### ISSUE TITLE
dynamic ordering

### ISSUE THREAD

**Issue by GitHubish** [fknop/angular-pipes#24]
Hello,

I notice that if my data is modified the re-sorting (re-ordering) is not working. Is this normal ? Or what should I do for it to be the case.

**Example:**

`
private values = [
     { name: 'a', order: 1},
     { name: 'b', order: 2},
     { name: 'e', order: 5}
];
`

`
<div *ngFor="let value of values | orderBy : 'order'">
     {{ value.name }} = {{ value.order }}
</div>
`

`onClick() {
     this.values[2].order = 4;
}`

The value is changed but the loop does not re-sort .

Thank you

**Comment by fknop** [comment]
You need to use immutability. All the pipes are pure for performance reasons.
