### ISSUE TITLE
Support for Angular 2 final

### ISSUE THREAD

**Issue by rafaelss95** [fknop/angular-pipes#25]
Are there any plans to support Angular2 Final?

**Comment by fknop** [comment]
If I'm not wrong it should work. I didn't actually try it (lack of time) but there was no changes to pipes between rc.6 and final.

Do you have errors trying to use it ?

**Comment by fknop** [comment]
I just published the `4.0.0` version tested with Angular Final `2.1.0`. 
The files `src/math.ts`, `src/array.ts`, etc. have been moved as `index.ts` in their respective folder. It may have caused issues with AOT.

If another error occurs, you can open another issue.
