### ISSUE TITLE
If needed more string examples, you can copy from....

### ISSUE THREAD

**Issue by born2net** [fknop/angular-pipes#28]
If needed more string examples, you can copy from....
https://github.com/jprichardson/string.js

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by fknop** [comment]
Hi, 

I don't have time at the moment to look at it. But if someone want to suggest a new pipe, I'll be happy to accept a PR.
