### ISSUE TITLE
"aggregate functions" should be the name of the group for min, max, sum (etc)

### ISSUE THREAD

**Issue by paul-hammant** [fknop/angular-pipes#3]
https://en.wikipedia.org/wiki/Aggregate_function

- A super well known term that will boost instant underderstanding from people with SQL knowledge.

Also a highly attractive Angular feature deleted before Angular 1.0 :-(

**Comment by fknop** [comment]
I agree that `Math` is not the best name for this. I'll do this for `1.4.0` (this week-end !).

Thank you :+1:

**Comment by born2net** [comment]
getting some nice stars on this project ;)

**Comment by fknop** [comment]
I'll accept a PR if someone wants to reorganize the docs accordingly.

**Comment by fknop** [comment]
I'm pushing this back a little bit to focus on new pipes first.

**Comment by fknop** [comment]
I'll probably do that tomorrow, I'll keep references to theses pipes in the math category for now to avoid breaking changes.
