### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by anxing131** [fknop/angular-pipes#32]
i'm follow document install and inport NgPipesModule in my AppModule, eg : 
![image](https://cloud.githubusercontent.com/assets/23404814/20996104/2e7e6fc6-bd36-11e6-8dc2-5b91fb0626dc.png)

but i do it is no working, i'm find some Erorr info in Chrome console : 
![image](https://cloud.githubusercontent.com/assets/23404814/20996158/825b489e-bd36-11e6-944d-c23461507354.png)

Environment :
  Win7_x64
  Webstore
  Angular(2.2.0)
  SystemJs

**Comment by fknop** [comment]
Remove the `/src~`

**Comment by anxing131** [comment]
i already remove `/src`, but still throw same Errors in Chrome

**Comment by fknop** [comment]
Did you map angular-pipes in your SystemJS config file ?

**Comment by anxing131** [comment]
my SystemJs config file is default, i not map angular-pipes to it

`/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (sdf, sdf2) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/',
            'rxjs': 'node_modules/rxjs',
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: './src',
            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            // other libraries
            'rxjs':                      'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api',
            'angular2-data-table': 'node_modules/angular2-data-table/release',
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                // defaultExtension: 'js'
                'rxjs': { main: 'bundles/Rx.min.js', defaultExtension: 'js' }
            },
            'angular-in-memory-web-api': {
                main: './index.js',
                defaultExtension: 'js'
            },
            'angular2-data-table': {
                main: './index.js',
                defaultExtension: 'js'
            },
        }
    });
})(this);`

**Comment by fknop** [comment]
You need to add `angular-pipes: npm:angular-pipes` in the map object. 

The problem coming from SystemJS, I'm closing this issue.
