### ISSUE TITLE
I recommend merging with https://github.com/danrevah/ngx-pipes

### ISSUE THREAD

**Issue by born2net** [fknop/angular-pipes#36]
I recommend merging with https://github.com/danrevah/ngx-pipes

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by fknop** [comment]
I can't really afford to merge this project into another as users and companies rely on it. I know there are some companies that are using this project in production. 

His project looks newer than mine (which is almost one year old already), if the maintainer is ready to merge with me and maybe move the project to an organization on GitHub. I'll be glad to do it after discussing the subject with him.

**Comment by born2net** [comment]
understood, just thought I will bring it up
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean
