### ISSUE TITLE
Bundling / packaging issue ? Comment here!

### ISSUE THREAD

**Issue by fknop** [fknop/angular-pipes#37]
If you encounter a bundling or packaging issue, comment here!

I'm planning to change the bundling / packaging setup to include UMD bundles and tree-shakeable code. I prefer having a centralized issue for this.

**Comment by fknop** [comment]
No issue have been reported in a month. Closing this for now.

**Comment by ChristosGeorgiou** [comment]
I think that I found something going wrong. I try to build for prod but cli fails
```
ERROR in ./node_modules/angular-pipes/src/math/bytes.pipe.ts
Module build failed: Error: C:\...\node_modules\angular-pipes\src\math\bytes.pipe.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\...\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (C:\...\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/modules/marketing/presentations/components/item/item.component.ngfactory.js 20:23-67
 @ ./src/modules/marketing/presentations/presentations.module.ngfactory.js
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```
I have tried to include the module only, the pipes only and various other combinations.

**Comment by gschafra** [comment]
Also here with 

> ng build --prod 

`     [exec] [0m[1m[31mERROR in ./node_modules/angular-pipes/src/object/keys.pipe.ts[39m[22m[0m
     [exec] [0m[1m[31mERROR in ./node_modules/angular-pipes/src/object/keys.pipe.ts[39m[22m[0m
     [exec] [0m[1m[31mModule build failed: Error: /var/data/workspace/sws/SALT/node_modules/angular-pipes/src/object/keys.pipe.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.[39m[22m[0m
     [exec] [0m[1m[31mModule build failed: Error: /var/data/workspace/sws/SALT/node_modules/angular-pipes/src/object/keys.pipe.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.[39m[22m[0m
     [exec] [0m[1m[31mThe missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).[39m[22m[0m
     [exec] [0m[1m[31mThe missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).[39m[22m[0m
     [exec] [0m[1m[31m    at AngularCompilerPlugin.getCompiledFile (/var/data/workspace/sws/SALT/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)[39m[22m[0m
     [exec] [0m[1m[31m    at AngularCompilerPlugin.getCompiledFile (/var/data/workspace/sws/SALT/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)[39m[22m[0m
     [exec] [0m[1m[31m    at plugin.done.then (/var/data/workspace/sws/SALT/node_modules/@ngtools/webpack/src/loader.js:467:39)[39m[22m[0m
     [exec] [0m[1m[31m    at process._tickCallback (internal/process/next_tick.js:109:7)[39m[22m[0m
     [exec] [0m[1m[31m    at plugin.done.then (/var/data/workspace/sws/SALT/node_modules/@ngtools/webpack/src/loader.js:467:39)[39m[22m[0m
     [exec] [0m[1m[31m    at process._tickCallback (internal/process/next_tick.js:109:7)[39m[22m[0m
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.`

@angular/cli v1.7.1
Angular v5.2.6
angular-pipes v6.5.3

**Comment by fknop** [comment]
I'm going ot publish a new version following the angular package format as `@next` tag for now. If it works without issues, I'm going to publish it as main version.

**Comment by fknop** [comment]
You can now try installing with `npm i angular-pipes@next -S`.

**Comment by gschafra** [comment]
On 

> ng serve --prod

I've got

`
ERROR in : Unexpected value 'NgArrayPipesModule in D:/vlinux/frontend/salt/node_modules/angular-
pipes/angular-pipes.d.ts' imported by the module 'OrdersModule in D:/vlinux/frontend/salt/src/ap
p/appdata/orders/orders.module.ts'. Please add a @NgModule annotation.
`

within following module definition

```typescript
import { NgArrayPipesModule, NgObjectPipesModule } from 'angular-pipes';

@NgModule({
	imports: [
		NgArrayPipesModule,
		NgObjectPipesModule
         [
...
})
export class OrdersModule
{
}
```

What I am doing wrong?

**Comment by fknop** [comment]
Could you provide a minimal reproduction of the issue ?

**Comment by papagei9** [comment]
Production build is not working.

angular-pipes v7.0.1
```javascript
ERROR in : Unexpected value 'BytesPipe in C:/Users/xxx/Documents/xxx/xxx/xxx/xxx-ui/node_modules/angular-pipes/angular-pipes.d.ts' declared by the module 'AdminModule in C:/Users/xxx/Documents/xxx/xxx/xxx/xxx-ui/src/app/admin/admin.module.ts'.
 Please add a @Pipe/@Directive/@Component annotation.
```

**Comment by fknop** [comment]
Are you using the CLI ?

I've tried with a CLI repository, it worked. If you're not using the CLI, could you please provide a minimal reproduction so that I can trace the error ?

**Comment by josp70** [comment]
I have created a repository which reproduces the error in production build. It happens either when `ng build --aot` or `ng build --production`

https://github.com/josp70/TestAngularPipes

The error message is:

```
ERROR in : Unexpected value 'NgMathPipesModule in 
TestAngularPipes/node_modules/angular-pipes/angular-pipes.d.ts' imported by the module
'AppModule in Angular/TestAngularPipes/src/app/app.module.ts'. Please add a @NgModule annotation.
```

**Comment by fknop** [comment]
I think I know where the error comes from. I'll take a look into it later this evening.

**Comment by fknop** [comment]
Issue is probably resolved now, it was an issue with `ng-packagr` or AOT which didn't generate metadata when exporting `*` from a `index.ts`. I changed every export to explicit export, and it should now work with version `7.1.0`.

**Comment by josp70** [comment]
I confirm that this issue is solved.

thanks!!!

**Comment by gethinoakes** [comment]
I'm getting a 'Metadata version mismatch' error when serving my CLI project, it only happens on the first run and when I save a file it compiles successfully. No errors in the web app itself and the pipes seem to work just fine.

```
ERROR in Error: Metadata version mismatch for module /.../node_modules/angular-pipes/angular-pipes.d.ts, found version 4, expected 3, resolving symbol AppModule in /./src/app/app.module.ts, resolving symbol AppModule in.. /.../src/app/app.module.ts
```

Any ideas? Thanks in advance :)

**Comment by fknop** [comment]
What version of angular are you using ?

**Comment by gethinoakes** [comment]
4.0.3, is 5 minimum for this?

**Comment by fknop** [comment]
Yes, I think the AOT metadata on the latest version is not compatible with the V4 compiler. You could try to make it work with an older version of angular-pipes.

**Comment by fknop** [comment]
I'm gonna do a little bit of research to see if it's not possible to generate multiple versions.

**Comment by gethinoakes** [comment]
Thanks. We'll be in the process of moving to angular 5 soon and will check this library out again then, we've managed a different solution for now.
