### ISSUE TITLE
v1.4.0 Notes

### ISSUE THREAD

**Issue by fknop** [fknop/angular-pipes#4]
# v1.4.0 Notes (not a release note)

I will bring new pipes soon. Here are some I can think about. If you have ideas, I'll take it :+1: .
Everything is probably not coming for next version. `1.4.0` will come at the latest end of next week. If anyone wants to contribute, you're welcome !

## String 

* [x] `capitalize` 
* [x] `upperfirst`
* ~~`camelcase`~~ (next release)
* ~~`snakecase`~~ (next release)
* [x] `template`
    + `{{ 'This $1 the $2 pipe' | template: 'is': 'template' }}`
* [x] `encodeURI`
    + The encodeURI function
* [x] `encodeURIComponent`
    + The encodeURIComponent function
* [x] `repeat`
* [x] `truncate`

## Collections

* [x] `shuffle`

## Math

* [x] `random`

## Pure pipes

* Impure pipes can be a performance hit because the pipe is executed for every change detection. So, for those who don't need impure pipes, I'll probably do pure versions.
https://github.com/fknop/angular-pipes/issues/5

## Aggregate group

* Issue: https://github.com/fknop/angular-pipes/issues/3

**Comment by born2net** [comment]
I think validators / formatters would be nice (email, zip etc...) most of the code can be imported from https://github.com/chriso/validator.js

**Comment by born2net** [comment]
I will soon contribute credit card tester

**Comment by born2net** [comment]
and if you really want to go wild :)
https://www.codefellows.org/blog/the-ten-best-javascript-libraries-for-form-validation-and-formatting

**Comment by fknop** [comment]
Formatters are a good idea. But it would be nice to keep this library without dependencies.

I think pipes with dependencies like [angular2-moment](https://github.com/urish/angular2-moment) should be kept in a separate library. So you don't have to download all this dependencies if you don't want to.

**Comment by born2net** [comment]
sure whatever you think is best, but I wasn't really thinking of adding as a dependency, more so of copying and pasting the code snippets and injecting as part of your lib (all these are MIT licences so as long as you add some credit you are fine copying and pasting)

**Comment by fknop** [comment]
Ok. Sounds good.

**Comment by fknop** [comment]
Little update: New pipes are on `master`, I still need to do some tests. I'm removing `camelcase` and `snakecase` from this release.

**Comment by born2net** [comment]
Great, by the way, if you wanted to add Credit card pipe, I have all the logic here: https://github.com/born2net/studioDashboard/blob/master/src/services/CreditService.ts 
so it will be trivial for you to make a pipe of.. it's a very strong algorithm for CC validation as well as CC type check...

**Comment by fknop** [comment]
@born2net Hi, thanks. It would be nice if you could do a PR. I'm a little bit busy for the moment.

**Comment by born2net** [comment]
np, I understand, will add to my to-do...
regards

**Comment by fknop** [comment]
`1.4.0` is published on `npm` ! Docs is coming tomorrow or saturday.
