### ISSUE TITLE
number pipes hides the built-in DecimalPipe

### ISSUE THREAD

**Issue by nirsalon** [fknop/angular-pipes#40]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
when using angular-pipes, we can't use the built-in DecimalPipe anymore (also a number pipe)
https://angular.io/docs/ts/latest/api/common/index/DecimalPipe-pipe.html

**Expected behavior**
Either rename this number pipe, or give a workaround

**Comment by fknop** [comment]
It's probably best to rename the pipe. It will have to be a major version.

In the meantime, you can still import the modules you need or the pipes you need to avoid importing the `number` pipe.
