### ISSUE TITLE
missing 'first' pipe

### ISSUE THREAD

**Issue by nirsalon** [fknop/angular-pipes#41]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
```

**Current behavior**
No pipe returns the first element that matches a condition

**Expected behavior**
A new pipe, similar to 'where', that returns the first element that matches the condition
See .NET linq .First() https://msdn.microsoft.com/en-us/library/bb535050(v=vs.110).aspx

**What is the motivation / use case for changing the behavior?**
A more performant pipe than (arr | where:[cond])[0]

**Comment by fknop** [comment]
That's a good idea, what about the `firstWhere` name ?

**Comment by nirsalon** [comment]
C# uses `First()`, and `FirstOrDefault()` which doesn't throw if not found
Java 8 uses `findFirst()`
Usually function names are either `verb` or 'verbNoun', so I'd say something like `first`/`firstMatch`/`findFirst`, but `firstWhere `also work.

**Comment by fknop** [comment]
I think I'll go with `firstOrDefault`. 

I'll probably implement that with https://github.com/fknop/angular-pipes/issues/40 tonight or tomorrow.
