### ISSUE TITLE
Merging projects `angular-pipes` with `ngx-pipes`

### ISSUE THREAD

**Issue by danrevah** [fknop/angular-pipes#42]
https://github.com/danrevah/ngx-pipes

Contact me to see if we can merge our projects.
danrevah89@gmail.com

**Comment by fknop** [comment]
I don't have a lot of time right now. I'm probably going to contact you next week.

**Comment by KyleCartmell** [comment]
[next week?](https://i.imgflip.com/1uvg85.jpg)

**Comment by KyleCartmell** [comment]
![next week?](https://i.imgflip.com/1uvg85.jpg)

**Comment by fknop** [comment]
@danrevah If you wish to take the code, go ahead. The license is MIT after all.
