### ISSUE TITLE
Tests for encodeUri interchanged

### ISSUE THREAD

**Issue by Aides359** [fknop/angular-pipes#44]
**I'm submitting a ...** 

```
[x] bug report
[ ] feature request
```

**Current behavior**

The tests for `encodeUri` and `encodeUriComponent` are probably interchanged.
`encodeUri` should encode a full URI while `encodeUriComponent` should only encode a sequence of chars.

**Expected behavior**

`encodeUri` should test with `https://test.com`.
`encodeUriComponent` should test with `éà`.

**Comment by fknop** [comment]
I'm not sure I understand why you mean.

The results:

```javascript
encodeURI('éà');
// %C3%A9%C3%A0

encodeURI('http://test.com');
// http://test.com

encodeURIComponent('http://test.com');
// http%3A%2F%2Ftest.com

encodeURIComponent('éà');
// %C3%A9%C3%A0
```

**Comment by Aides359** [comment]
The results are as expected and since comparing to the function output in the test they do indeed succeed.

However IMO they miss the intend of the function as `encodeURIComponent` should rather be used for a full URI as `https://test.com` or even `http://test.com/some/custom/réàöß/uri?with=params`.
In the test the function is only tested for two characters which would rather be the use-case for `encodeURIComponent` while `encodeURIComponent` is tested with a full URI which again kind of misses the intend of the function.

**Comment by fknop** [comment]
I will add the same tests for both functions.

I did not bother adding more tests to these pipes as it's just calling a built-in function that shouldn't return unexpected result.
