### ISSUE TITLE
--strictNullChecks

### ISSUE THREAD

**Issue by Aides359** [fknop/angular-pipes#45]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**

When imported in a project with --strictNullChecks `with.pipe.ts` throws with `Type 'null' is not assignable to 'string'`
angular-pipes does not use --strictNullChecks.

**Expected behavior**

When imported in a project with --strictNullChecks no errors should be thrown.
Use --strictNullChecks and require pipes to be written for --strictNullChecks

**Minimal reproduction of the problem with instructions**
Clone master and add `"strictNullChecks": true,` to `tsconfig.json`.

**What is the motivation / use case for changing the behavior?**

Using angular-pipes in any project with --strictNullChecks throws compiler errors in dependencies. Also the type definitions do not include null and undefined types.
Code written for --strictNullChecks does not have any impact for projects not using this flag.

**Possible drawbacks**
Writing code for --strictNullChecks is slightly more expensive, however since pipes should be short and simple functions this should be acceptable.

**Comment by fknop** [comment]
I'm aware of this issue. I'm fixing this tomorrow.

**Comment by Aides359** [comment]
No need, PR pending ;)

**Comment by fknop** [comment]
Thanks, reviewing it later :)
