### ISSUE TITLE
Please suggest OrderBy usage for this Json

### ISSUE THREAD

**Issue by just10minutes** [fknop/angular-pipes#52]
Hi,

This is not a Bug or issue. Please consider this as Info/Request

I have the below data with me in json format.

This is the list of comments. In this example 19 comments are there under items tag.

http://www.jsoneditoronline.org/?id=47b282c498505ed25869dc36f5f3bd58

Comments are sorted based on Date published.

Now on the Item Id 10th there are two replies to this comment.

I am looking for a way to order this reply based on publishedAt time.

Below is my html: 
Here videoComments = the json data specified above

```
<ion-list>
  <ion-item *ngFor="let comment of videoComments">
    <!-- here i Print the details what is required , next if there are any reply i would like to show them-->   
    <div *ngIf="comment.snippet.totalReplyCount != 0">
      <ion-list>
        <ion-item *ngFor="let reply of comment.replies.comments | orderBy: 'publishedAt'"> 
          <!-- Above orderBy pipe is not working , may be my syntax is wrong -->
           <!-- I would like to show replies in ascending order of when it was submitted-->
          <!-- Details of replies will be shown here -->          
        </ion-item>
      </ion-list>
    </div>
  </ion-item>
</ion-list>
```

Your assistance is highly appreciated.

**Comment by fknop** [comment]
Hi, looks like you need to transform your date which is in string format into an instance of Date first. Otherwise a sort on the string will be done, which is probably not what you would expect.

**Comment by just10minutes** [comment]
@fknop Thank you for the very quick response. You are right I will definitely look at your suggestion.

I believe my way of providing the key for the orderBy pipe is not right. Let's assume publishedAt value is string, I tried both ' publishedAt' and '-publishedAt' this did not change the result. it should have changed the reault as both the values are not same for two replies of the comment.

Thanks

**Comment by just10minutes** [comment]
@fknop do you think this syntax is correct to fetch replies, based on my Json object?

<ion-item *ngFor="let reply of comment.replies.comments | orderBy: 'publishedAt'"> 

Thanks
