### ISSUE TITLE
Angular 5 compatibility

### ISSUE THREAD

**Issue by pmcochrane** [fknop/angular-pipes#54]
I'm suspecting that angular-pipes is not compatible with angular 5. Do you know whether it is or not?

Uncaught TypeError: core_1.OpaqueToken is not a constructor
    at Object.<anonymous> (utils.ts:341)
    at __webpack_require__ (utils.ts:341)
    at Object.module.exports (utils.ts:341)
    at __webpack_require__ (utils.ts:341)
    at Object.<anonymous> (utils.ts:341)
    at __webpack_require__ (utils.ts:341)
    at Object.<anonymous> (utils.ts:341)
    at __webpack_require__ (utils.ts:341)
    at Object.lineBreak (utils.ts:341)
    at __webpack_require__ (utils.ts:341)

Sorry for the lack of other information but any guidance is appreciated.

**Comment by fknop** [comment]
Are you sure this is coming from angular-pipes ? OpaqueToken is not used in this project.

**Comment by ReinierGielen** [comment]
I added angular pipes to a working Angular 5 project and  it broke. it is nor compiling:
2017-11-10T20:37:34.014ZERROR in ./node_modules/angular-pipes/src/array/order-by.pipe.ts

Hash: 49520dc6bdc2e6bec19c
Time: Module build failed: Error: D:\WebstormProjects\prime\primetest\node_modules\angular-pipes\src\array\order-by.pipe.ts is not part of the compilation output. Please check the other error messages for details.9837
ms
    at AngularCompilerPlugin.getCompiledFile (D:\WebstormProjects\prime\primetest\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)chunk {
inline}     at plugin.done.then (D:\WebstormProjects\prime\primetest\node_modules\@ngtools\webpack\src\loader.js:467:39)inline.bundle.js
 (inline) 5.79 kB [entry]    at process._tickCallback (internal/process/next_tick.js:103:7) [rendered]

**Comment by fknop** [comment]
I think this is a angular related issue where the file might not be included in the compilation, there is a lot of issues about that on the angular repo or cli, you might want to take a look

**Comment by pmcochrane** [comment]
I'm not sure if there  is an error or not. Trying to upgrade my app to angular 5 and only reporting this as it was complaining about utils.ts which is part of this module. I have commented all angular-pipes out of the code for now and will let you know if I progress any further after more debugging. 

I was just asking in case you had previously tested with angular 5 or not to save me some time. Thanks for your input.

**Comment by fknop** [comment]
I did not test it myself with version 5. But I see no reasons why it should break. I saw some people having the same message as yours on other modules tho.

**Comment by pmcochrane** [comment]
I think this may be a false positive in that other errors are falling back to reporting the error as being in utils.ts 
I'm having issues with trying to get angular-material to work as there have been a few changes for the move to angular 5 and I think this is where the issues are.

**Comment by pmcochrane** [comment]
Sorry for the confusion. My app is showing the error as being from this library but in fact the error is elsewhere in the code. Unfortunately, the console logging is not showing the correct line in the source code for where the error actually is which is just plain annoying but not anything to do with angular pipes.

Thanks
