### ISSUE TITLE
is this for angularJS or angular?

### ISSUE THREAD

**Issue by halukkaramete** [fknop/angular-pipes#57]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Comment by fknop** [comment]
> angular-pipes is a pipes library for Angular.
