### ISSUE TITLE
Limit Pipe?

### ISSUE THREAD

**Issue by aaronfrost** [fknop/angular-pipes#58]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
```

Just wondering if there are plans to add a `limit` pipe for collections, so that you can reduce the size of the collection. An example of this would be if you `ngFor` over a large collection, you could do a limit pipe to reduce the output sized of the items. 

If this already exists, please forgive me. I looked through the documentation and couldn't see it.

**Comment by fknop** [comment]
I think you're looking for the `take` pipe. https://github.com/fknop/angular-pipes/blob/master/docs/array.md#take

**Comment by aaronfrost** [comment]
Thank you @fknop! I appreciate the guidance.
