### ISSUE TITLE
Typo in "truncate" documentation

### ISSUE THREAD

**Issue by GoGoris** [fknop/angular-pipes#62]
**I'm submitting a ...**

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

https://github.com/fknop/angular-pipes/blob/master/docs/string.md#truncate

**Current behavior**

> **Usage**
> ```javascript
> ...
> {{ 'Hello World, how is it going?' | truncate: 14: '...', true }} 
> ```

**Expected behavior**

**',' before the last pipe arguments should be ':'**

> **Usage**
> ```javascript
> ...
> {{ 'Hello World, how is it going?' | truncate: 14: '...': true }} 
> ```

**Minimal reproduction of the problem with instructions**

N/A

**What is the motivation / use case for changing the behavior?**

This typo caused confusion with a colleague who just started on the project. He thought that there was something wrong with the pipe but it was just a typo in the documentation.

**Comment by fknop** [comment]
Thank you, it's fixed
