### ISSUE TITLE
Angular 6 compatibility

### ISSUE THREAD

**Issue by jscharett** [fknop/angular-pipes#63]
Plans for Angular 6 compatibility?

**Comment by fknop** [comment]
I will make a new version for the final release of v6.

If you want in the meantime you can update ng-packagr for v6 and create a pull request with the new dependencies.

**Comment by fknop** [comment]
I've published `8.0.0-rc.0` with tag `next` with `rc` versions of Angular 6 and `ng-packagr`. Note that I have not tried this.
