### ISSUE TITLE
When performing a build in Angular 6, compiler complains about not finding a module

### ISSUE THREAD

**Issue by hunt3ri** [fknop/angular-pipes#65]
When I perform an ng-build with the --prod flag under Angular 6 I see the following error.  It seems to be related to this issue.  Version is 7.2

[Github link](https://github.com/angular/angular-cli/issues/8284)

ng build project --prod

ERROR in src/app/admin/customers/customer-details/customer-details.component.ts(7,29): error TS2307: Cannot find module 'angular-pipes/src/array/order-by.pipe'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapcloud-portal@0.0.0 dist-mc: `ng build mapcloud --prod --output-path ../server/portal/web/static/dist/en`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapcloud-portal@0.0.0 dist-mc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\iain.hunter\AppData\Roaming\npm-cache\_logs\2018-05-18T16_42_31_181Z-debug.log

**Comment by fknop** [comment]
There was a rc version 8.0.0 for Angular 6. I'm going to publish final 8.0.0 right now.

**Comment by fknop** [comment]
Version `8.0.0` has been published, it should work now.

**Comment by hunt3ri** [comment]
Hi thanks, for the super quick response.  I just tried building now, and it's all compiling again 💯
