### ISSUE TITLE
with pipe is not working if anything passed to it! and other...

### ISSUE THREAD

**Issue by Et3rnal** [fknop/angular-pipes#67]
**I'm submitting a bug

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```
**Current behavior**
Through the error "Parser Error: Unexpected token ',' at column 32 in [ {{ 'Sarmad et3rnal' | with: null,null,true }} ] in ng:///TheMagicsModule

**Expected behavior**
Just return the text

**Minimal reproduction of the problem with instructions**
I'm on Angular 6, I have installed this in hope to use the "with" pipe.
I have tested other pipes in the string module and they are working just fine except for 
wrap: '{{': '}}'
Which is throwing a different error "Unexpected token Lexer Error: Unterminated quote..."

**Comment by fknop** [comment]
It looks like I made an error in the documentation. `:` should be used to separate arguments and not `,` which is why the parser complains.

**Comment by Et3rnal** [comment]
Great that was easy. I was worried Angular 6 break it 💃

**Comment by Et3rnal** [comment]
You forget to fix the first one ?
{{'The Flash Reverse' | with: 'The' : null, true}}
