### ISSUE TITLE
Split returned value is not comparable? 

### ISSUE THREAD

**Issue by Et3rnal** [fknop/angular-pipes#72]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

After splitting a string, I tried to compare (==) the result but it always returns false

**Expected behavior**

To return true when values match

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Even if I put the same text on both it returns false after the text goes through the split pipe
`{{ ('ss::aa::zz' | split: '::' : 1 ) == ('ss::aa::zz' | split: '::' : 1 ) }}`
printing the results seems to be identical!

PS: plnkr template doesn't work!

**Comment by fknop** [comment]
This is the way arrays work in JavaScript. Test `[1,2,3] == [1,2,3]` in your JS console, it will return also return false. If you want to compare two arrays you need to use a function that compares each element.

**Comment by Et3rnal** [comment]
Because the printed value didn't include the brackets I thought it's not one item inside an array anymore. Anyway, this is how I solved without a function
`{{ ('ss::aa::zz' | split: '::')[0] == ('ss::aa::zz' | split: '::')[0] }}`

Thank you
