### ISSUE TITLE
Code for version 9.x?

### ISSUE THREAD

**Issue by leonardochaia** [fknop/angular-pipes#77]
Hi, I removed the issue template since this does not seem to fit.
I'm updating a project to Angular 7 and I'm looking for the changelog of v9.0.0 which I can't seem to find.
I can see on npm v9.0.0 published 19/10/2018 but the master branch seems to be from version 8.1.0 according to the  `package.json`?. Latest changelog entry is from 8.0.0. Latest release in Releases page is v5.0.8.

Is there something I'm missing? where's the code for version 9.x ?

Thanks,
Leo.

**Comment by fknop** [comment]
I must have forgot to push it. 9.0.0 is for Angular 7. https://github.com/fknop/angular-pipes/issues/76

Pushing it ASAP.

**Comment by fknop** [comment]
Code is pushed, last version is 9.0.1 in which I added a missing pipe from version 9.0.0. 

https://github.com/fknop/angular-pipes/blob/master/CHANGELOG.md

Thanks!

**Comment by leonardochaia** [comment]
Thank you @fknop !
