### ISSUE TITLE
Incorrect Ordinals

### ISSUE THREAD

**Issue by larjohn** [fknop/angular-pipes#83]
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

Ordinals from 11 to 13 are not correct (11st, 12nd, 13rd)

**Expected behavior**

They should be 11th, 12th, 13th
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Comment by fknop** [comment]
I'll try to make a fix ASAP

**Comment by christopheelkhoury** [comment]
@fknop I can take care of it if you like

**Comment by fknop** [comment]
@christopheelkhoury I would appreciate it, thanks

**Comment by christopheelkhoury** [comment]
@fknop on it. Should be done by 6 PM GMT 😃

**Comment by christopheelkhoury** [comment]
Nvm done
