### ISSUE TITLE
Unable to use where pipe

### ISSUE THREAD

**Issue by thxmike** [fknop/angular-pipes#93]
**I'm submitting a ...**  (check one with "x")

```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
Ang
Error when using the where filter:
Uncaught Error: Template parse errors:
The pipe 'where' could not be found ("               <mat-nav-list dense>
                    <mat-list-item *ngFor="let securityInvestiga[ERROR ->]tion of securityInvestigations | where: ['securityInvestigation.product_id', selectedProduct.id]" >{{"): ng:///NavigationModule/InvestigationComponent.html@16:64

**Expected behavior**
filtered collection of securityInvestigations

**Minimal reproduction of the problem with instructions**
 npm install angular-pipes --save

Imported the module to the app.module:
import { NgArrayPipesModule } from 'angular-pipes';

Imported the where type to the component.ts:
import { WherePipe } from 'angular-pipes';

Added the following pipe to the component.html
<mat-list-item *ngFor="let securityInvestigation of securityInvestigations | where: ['securityInvestigation.product_id', selectedProduct.id]" >{{securityInvestigation.date}}</mat-list-item>

I am looking to filter datasets by particular id. Perhaps I am missing a step. I am not quite sure how to troubleshoot this.  Any guidance would be appreciated.

ng version
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

**Comment by thxmike** [comment]
I believe I found the problem. I am using nested modules. I loaded it on my top level module but it did not inherit down to the child module. As soon as I added it to my child module, it appears to work

**Comment by fknop** [comment]
@thxmike Great :)

By the way, you don't need to import the WherePipe in your component: `import { WherePipe } from angular-pipes';`. Importing it in the module of your component is enough.
